export const funnyPlantNames = [
	'Spross Reynolds',
	'Fernando die Ficus',
	'Pepper der Kaktus',
	'Basilikum Fawlty',
	'Zweiggy Stardust',
	'Gänseblümchen Duke',
	'Blattluma',
	'Petersilie Jackson',
	'Blatt Erikson',
	'Sir Schnittgesicht',
	'Olive Wirbelwind',
	'Coco Chanelle',
	'Bambuselt',
	'Snoop Dogwood',
	'Zweiggy Smalls',
	'Flora Dora',
	'Dornige Rose',
	'Kaktina Minogue',
	'Lass uns Salat beten',
	'Zweiggy Marley',
	'Holly Leichtfuß',
	'Cedar Skywalker',
	'Basilikum der Große',
	'Wein Diesel',
	"Oscar Wilde'n'see",
	'Löwenzahnär',
	'Feigen Azalee',
	'Herr Ananas',
	'Geigenblatt Newton',
	'Wurzel Goldberg',
	'Petunie Schwein',
	'Bambus-Buh!',
	'Hyazinthe Eimer',
	'Petersilie Geschlagen',
	'Oprah Baumfrey',
	'Gänseblümchen Buchanan',
	'Sir Willows-a-Lot',
	'Demi Lovato Pflanze',
	'Sherlock Gartenzwerg',
	'Fernando Valenzuela',
	'Stachelrücken',
	'Bonsai der Riese',
	'Chia die Bombe',
	'Wanda die Wanderrute',
	'Kohl Sagan',
	'Salbei der Gemini',
	'Tulpe Neanderthalensis',
	'Drake die Schlangenpflanze',
	'Distel Beckham',
	'Jasmin Timberlake',
	'Beyonsee',
	'Ingwer Wurzel Rogers',
	'Koriander Schurke',
	'Granatapfel Pitt',
	'Rhabarber Downey Jr.',
	'Pastinake Hilton',
	'Gänseblümchen Ridley',
	'Sir Reginald Blattington',
	'Aloe Blacc',
	'Fenchel Schmidt',
	'Bruce Sprengsteen',
	'Weide Schmidt',
	'Efeutute Malone',
	'Katy Perennial',
	'Sylvester Stalagmit',
	'Sebastian der Crabapple',
	'Heidelbeer Houndstooth',
	'Blüte Gallagher',
	'Blatt Garrett',
	'Gänseblümchen Dukes of Hazzard',
	'Pastinake Turner',
	'Sesam Zeder',
	'Zitronig Snicket',
	'Sir Schnitt-a-lot',
	'Efeu Langstrumpf',
	'Pistazie Verkleidet',
	'Ringelblumen Globes',
	'Basilikum Rathbone',
	'Tulpe Cruise',
	'Zweiggy Lawson',
	'Ficus Alba',
	'Pfeffer Potts',
	'Lass uns Grohl',
	'Gänseblümchen Duke of Earl',
	'Zypressen Hügel',
	'Safran Connery',
	'Kürbis Ramsey',
	'Bambus Marley',
	'Thymian Lord',
	'Herr Rübe',
	'Zucchini Minnelli',
	'Koriander Spice',
	'Spargel Spears',
	'Jadeit Ritter',
	'Wisteria Lane',
	'Möhrenkopf',
	'Geranienmann',
	'Salbei Stallone',
	'Tofu McPlantface',
	'Basilisk',
	'Farn Gully',
	'Sprossnik',
	'Ananas Express',
	'Agave Adams',
	'Blumenkohl Power',
	'Stiefmütterchen Skywalker',
	'Lilie Potter',
	'Ziggy Stardust-Filament',
	'Rosmarins Baby',
	'Sukkulente Simpson',
	'Peperoni',
	'Tulpe Diddy',
	'Zweiggy Ramone',
	'Kohl Luthor',
	'Moos Malone',
	'Sellerie Dion',
	'Narzissma Hayek'
];
