/* eslint-disable */
/**
 * This file was generated by 'vite-plugin-kit-routes'
 *
 *      >> DO NOT EDIT THIS FILE MANUALLY <<
 */

/**
 * PAGES
 */
const PAGES = {
  "/": `/`,
  "/account": `/account`,
  "/dashboard": `/dashboard`,
  "/dashboard/sensor/[id=sensorId]": (params: { id: (ExtractParamType<typeof import('../params/sensorId.ts').match>) }) => {
    return `/dashboard/sensor/${params['id']}`
  },
  "/dashboard/sensor/[id=sensorId]/settings": (params: { id: (ExtractParamType<typeof import('../params/sensorId.ts').match>) }) => {
    return `/dashboard/sensor/${params['id']}/settings`
  },
  "/dashboard/sensor/new": `/dashboard/sensor/new`,
  "/dashboard/table": `/dashboard/table`,
  "/impressum": `/impressum`,
  "/privacy-policy": `/privacy-policy`,
  "/shop": `/shop`,
  "/tutorials/getting-started": `/tutorials/getting-started`,
  "/tutorials/home-assistant": `/tutorials/home-assistant`,
  "/selector": `/selector`,
  "/selector/sensor/new": `/selector/sensor/new`
}

/**
 * SERVERS
 */
const SERVERS = {
  "POST /api/auth/default/login": `/api/auth/default/login`,
  "POST /api/auth/default/register": `/api/auth/default/register`,
  "GET /api/auth/google/callback": `/api/auth/google/callback`,
  "POST /api/auth/google/login": `/api/auth/google/login`,
  "POST /api/auth/logout": `/api/auth/logout`,
  "GET /api/blumyWrl": `/api/blumyWrl`,
  "POST /api/cron": `/api/cron`,
  "DELETE /api/currentAccount": `/api/currentAccount`,
  "PUT /api/currentAccount/email": `/api/currentAccount/email`,
  "PUT /api/currentAccount/password": `/api/currentAccount/password`,
  "POST /api/sensorList": `/api/sensorList`,
  "POST /api/sensors": `/api/sensors`,
  "DELETE /api/sensors/[id]": (params: { id: (string | number) }) => {
    return `/api/sensors/${params['id']}`
  },
  "POST /api/sensors/[id]/check-subscription": (params: { id: (string | number) }) => {
    return `/api/sensors/${params['id']}/check-subscription`
  },
  "GET /api/sensors/[id]/image": (params: { id: (string | number) }) => {
    return `/api/sensors/${params['id']}/image`
  },
  "PUT /api/sensors/[id]/settings": (params: { id: (string | number) }) => {
    return `/api/sensors/${params['id']}/settings`
  },
  "POST /api/sensors/[id]/subscribe": (params: { id: (string | number) }) => {
    return `/api/sensors/${params['id']}/subscribe`
  },
  "POST /api/sensors/[id]/unsubscribe": (params: { id: (string | number) }) => {
    return `/api/sensors/${params['id']}/unsubscribe`
  },
  "POST /api/sensors/[id]/write-token": (params: { id: (string | number) }) => {
    return `/api/sensors/${params['id']}/write-token`
  },
  "POST /api/v2/data": `/api/v2/data`,
  "GET /api/v2/data": `/api/v2/data`,
  "POST /api/waitingList": `/api/waitingList`
}

/**
 * ACTIONS
 */
const ACTIONS = {
  
}

/**
 * LINKS
 */
const LINKS = {
  
}

type ParamValue = string | number | boolean | null | undefined

/**
 * Append search params to a string
 */
export const appendSp = (
  sp?: Record<string, ParamValue | ParamValue[]>,
  prefix: '?' | '&' = '?',
) => {
  if (sp === undefined) return ''

  const params = new URLSearchParams()
  const append = (n: string, v: ParamValue) => {
    if (v !== undefined) {
      params.append(n, String(v))
    }
  }

  let anchor = ''
  for (const [name, val] of Object.entries(sp)) {
    if (name === '__KIT_ROUTES_ANCHOR__' && val !== undefined) {
      anchor = `#${val}`
      continue
    }
    if (Array.isArray(val)) {
      for (const v of val) {
        append(name, v)
      }
    } else {
      append(name, val)
    }
  }

  const formatted = params.toString()
  if (formatted || anchor) {
    return `${prefix}${formatted}${anchor}`.replace('?#', '#')
  }
  return ''
}

/**
 * get the current search params
 * 
 * Could be use like this:
 * ```
 * route("/cities", { page: 2 }, { ...currentSP() })
 * ```
 */ 
export const currentSp = () => {
  const params = new URLSearchParams(window.location.search)
  const record: Record<string, string> = {}
  for (const [key, value] of params.entries()) {
    record[key] = value
  }
  return record
}

/* type helpers for route function */
type NonFunctionKeys<T> = { [K in keyof T]: T[K] extends Function ? never : K }[keyof T]
type FunctionKeys<T> = { [K in keyof T]: T[K] extends Function ? K : never }[keyof T]
type FunctionParams<T> = T extends (...args: infer P) => any ? P : never

const AllObjs = { ...PAGES, ...ACTIONS, ...SERVERS, ...LINKS }
type AllTypes = typeof AllObjs

export type Routes = keyof AllTypes extends `${string}/${infer Route}` ? `/${Route}` : keyof AllTypes
export const routes = [
	...new Set(Object.keys(AllObjs).map((route) => /^\/.*|[^ ]?\/.*$/.exec(route)?.[0] ?? route)),
] as Routes[]

/**
 * To be used like this: 
 * ```ts
 * import { route } from './ROUTES'
 * 
 * route('site_id', { id: 1 })
 * ```
 */
export function route<T extends FunctionKeys<AllTypes>>(key: T, ...params: FunctionParams<AllTypes[T]>): string
export function route<T extends NonFunctionKeys<AllTypes>>(key: T): string
export function route<T extends keyof AllTypes>(key: T, ...params: any[]): string {
  if (AllObjs[key] as any instanceof Function) {
    const element = (AllObjs as any)[key] as (...args: any[]) => string
    return element(...params)
  } else {
    return AllObjs[key] as string
  }
}

/* type helpers param & predicate */
type ExtractFnPredicate<T> = T extends (param: any) => param is infer U ? U : never;
type ExtractParamType<T extends (param: any) => any> = ExtractFnPredicate<T> extends never ? Parameters<T>[0] : ExtractFnPredicate<T>

/**
* Add this type as a generic of the vite plugin `kitRoutes<KIT_ROUTES>`.
*
* Full example:
* ```ts
* import type { KIT_ROUTES } from '$lib/ROUTES'
* import { kitRoutes } from 'vite-plugin-kit-routes'
*
* kitRoutes<KIT_ROUTES>({
*  PAGES: {
*    // here, key of object will be typed!
*  }
* })
* ```
*/
export type KIT_ROUTES = {
  PAGES: { '/': never, '/account': never, '/dashboard': never, '/dashboard/sensor/[id=sensorId]': 'id', '/dashboard/sensor/[id=sensorId]/settings': 'id', '/dashboard/sensor/new': never, '/dashboard/table': never, '/impressum': never, '/privacy-policy': never, '/shop': never, '/tutorials/getting-started': never, '/tutorials/home-assistant': never, '/selector': never, '/selector/sensor/new': never }
  SERVERS: { 'POST /api/auth/default/login': never, 'POST /api/auth/default/register': never, 'GET /api/auth/google/callback': never, 'POST /api/auth/google/login': never, 'POST /api/auth/logout': never, 'GET /api/blumyWrl': never, 'POST /api/cron': never, 'DELETE /api/currentAccount': never, 'PUT /api/currentAccount/email': never, 'PUT /api/currentAccount/password': never, 'POST /api/sensorList': never, 'POST /api/sensors': never, 'DELETE /api/sensors/[id]': 'id', 'POST /api/sensors/[id]/check-subscription': 'id', 'GET /api/sensors/[id]/image': 'id', 'PUT /api/sensors/[id]/settings': 'id', 'POST /api/sensors/[id]/subscribe': 'id', 'POST /api/sensors/[id]/unsubscribe': 'id', 'POST /api/sensors/[id]/write-token': 'id', 'POST /api/v2/data': never, 'GET /api/v2/data': never, 'POST /api/waitingList': never }
  ACTIONS: Record<string, never>
  LINKS: Record<string, never>
  Params: { 'id': never }
}
