#pragma once

#define DEFAULT_SENSOR_TIMEOUT_SLEEP_MS 1000 * 60 * 60 // 60 minutes
#define DEFAULT_CONFIGURATION_MODE_TIMEOUT_MS 60000

#define DEFAULT_SSID_MAX_LENGTH 33
#define DEFAULT_PASSWORD_MAX_LENGTH 65