export const funnyPlantNames = [
    "Sprout Reynolds",
    "Fernando the Ficus",
    "Pepper the Cactus",
    "Basil Fawlty",
    "Twiggy Stardust",
    "Daisy Duke",
    "Petaluma",
    "Parsley Jackson",
    "Leaf Erikson",
    "Sir Pruneface",
    "Olive Twister",
    "Coco Chanel",
    "Bamboo-zled",
    "Snoop Dogwood",
    "Twiggy Smalls",
    "Flora Dora",
    "Thorny Rose",
    "Cacti Minogue",
    "Lettuce Pray",
    "Twiggy Marley",
    "Holly Golightly",
    "Cedar Skywalker",
    "Basil the Great",
    "Vine Diesel",
    "Oscar Wilde'n'sea",
    "Dandelionaire",
    "Figgy Azalea",
    "Mr. Pineapple",
    "Fiddle Leaf Fig Newton",
    "Rooty Goldberg",
    "Petunia Pig",
    "Bamboo-boo",
    "Hyacinth Bucket",
    "Parsley Whipped",
    "Oprah Treefrey",
    "Daisy Buchanan",
    "Sir Willows-a-Lot",
    "Demi Lovato Plant",
    "Sherlock Gnomes",
    "Fernando Valenzuela",
    "Prickleback",
    "Bonsai the Giant",
    "Chia the Bomb",
    "Wanda the Wandering Jew",
    "Kale Sagan",
    "Sage the Gemini",
    "Tulip Neanderthalensis",
    "Drake the Snake Plant",
    "Thistle Beckham",
    "Jasmine Timberlake",
    "Beyonsea",
    "Ginger Root Rogers",
    "Cilantro Hitler",
    "Pomegranate Pitt",
    "Rhubarb Downey Jr.",
    "Parsnip Hilton",
    "Daisy Ridley",
    "Sir Reginald Leafington",
    "Aloe Blacc",
    "Fennel Smith",
    "Bruce Sprengsteen",
    "Willow Smith",
    "Pothos Malone",
    "Katy Perennial",
    "Sylvester Stalagmite",
    "Sebastian the Crabapple",
    "Huckleberry Houndstooth",
    "Blossom Gallagher",
    "Leaf Garrett",
    "Daisy Dukes of Hazzard",
    "Parsnip Turner",
    "Sesame Cedar",
    "Lemony Snicket",
    "Sir Prune-a-lot",
    "Ivy Longstocking",
    "Pistachio Disguisey",
    "Marigolden Globes",
    "Basil Rathbone",
    "Tulip Cruise",
    "Twiggy Lawson",
    "Ficus Alba",
    "Pepper Potts",
    "Lettuce Grohl",
    "Daisy Duke of Earl",
    "Cypress Hill",
    "Saffron Connery",
    "Gourd Ramsey",
    "Bamboo Marley",
    "Thyme Lord",
    "Mr. Beet",
    "Zucchini Minnelli",
    "Cilantro Spice",
    "Asparagus Spears",
    "Jadeite Knight",
    "Wisteria Lane",
    "Carrot Top",
    "Geranium Man",
    "Sage Stallone",
    "Tofu McPlantface",
    "Basilisk",
    "Fern Gully",
    "Sproutnik",
    "Pineapple Express",
    "Agave Adams",
    "Cauliflower Power",
    "Pansy Skywalker",
    "Lily Potter",
    "Ziggy Stardust-filament",
    "Rosemary's Baby",
    "Succulent Simpson",
    "Pepperoni",
    "Tulip Diddy",
    "Twiggy Ramone",
    "Kale Luthor",
    "Mossy Malone",
    "Celery Dion",
    "Daffodilma Hayek",
];
