#pragma once

#define DEFAULT_SENSOR_TIMEOUT_SLEEP_MS 1000 * 60 * 60 // 60 minutes
#define DEFAULT_CONFIGURATION_MODE_TIMEOUT_MS 60000
#define DEFAULT_WATCHDOG_TIMEOUT_MS 1000 * 20 // 20 seconds

#define DEFAULT_SSID_MAX_LENGTH 33
#define DEFAULT_PASSWORD_MAX_LENGTH 65
#define DEFAULT_API_URL "http://blumy.cloud/api/v2/data"
