version: '3.4'
name: esplant

services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-esplant}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-esplant}
      - POSTGRES_DB=esplant
    volumes:
      - ./db:/var/lib/postgresql/data

  server:
    image: ghcr.io/dennis960/esplant/server:${IMAGE_BRANCH:-main}.${IMAGE_NUMBER:-latest}
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-esplant}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-esplant}
      - POSTGRES_DB=esplant
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432

      - PUBLIC_VAPID_KEY=${PUBLIC_VAPID_KEY:?PUBLIC_VAPID_KEY not set}
      - PRIVATE_VAPID_KEY=${PRIVATE_VAPID_KEY:?PRIVATE_VAPID_KEY not set}
      - VAPID_EMAIL=${VAPID_EMAIL:?VAPID_EMAIL not set}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:?GOOGLE_CLIENT_ID not set}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET:?GOOGLE_CLIENT_SECRET not set}

      - BODY_SIZE_LIMIT=${BODY_SIZE_LIMIT:-Infinity}

      - ORIGIN=${ORIGIN:?ORIGIN not set. Set it to the URL of the server (e.g. http://localhost:3000 for dev).}
      - PORT=${PORT:-3000}
