version: '3.4'
name: esplant

services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-esplant}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-esplant}
      - POSTGRES_DB=esplant
    volumes:
      - db-data:/var/lib/postgresql/data

  server:
    image: server
    restart: always
    ports:
      - 5173:5173
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./Dockerfile.build
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-esplant}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-esplant}
      - POSTGRES_DB=esplant
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432

      - PUBLIC_VAPID_KEY=${PUBLIC_VAPID_KEY:?PUBLIC_VAPID_KEY not set}
      - PRIVATE_VAPID_KEY=${PRIVATE_VAPID_KEY:?PRIVATE_VAPID_KEY not set}
      - VAPID_EMAIL=${VAPID_EMAIL:?VAPID_EMAIL not set}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:?GOOGLE_CLIENT_ID not set}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET:?GOOGLE_CLIENT_SECRET not set}
      - PUBLIC_BASE_URL=${PUBLIC_BASE_URL:?PUBLIC_BASE_URL not set}

      - BODY_SIZE_LIMIT=${BODY_SIZE_LIMIT:-Infinity}


      - ENV PORT=5173
      - ENV ORIGIN=http://localhost:5173

volumes:
  db-data: