FROM node:20 AS build

WORKDIR /app

COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:20

WORKDIR /app

COPY --from=build /app/build ./build
COPY migrations ./migrations
COPY package*.json ./
RUN npm install --production

EXPOSE 3000
USER node
CMD ["node", "build/index.js"]