version: "3.4"
name: blumy-dev

services:
  db:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=blumy
      - POSTGRES_PASSWORD=blumy
      - POSTGRES_MULTIPLE_DATABASES=blumy,blumy_test
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
  server:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-20
    depends_on:
      - db
    ports:
      - 5173:5173
    command: sleep infinity
    environment:
      - POSTGRES_USER=blumy
      - POSTGRES_PASSWORD=blumy
      - POSTGRES_DB=blumy
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432

      - PUBLIC_MODE=test

volumes:
  db-data:
