FROM node:20-slim AS build

WORKDIR /app

COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM node:20-slim

WORKDIR /app

COPY --from=build /app/build ./build
COPY migrations ./migrations
COPY package*.json ./
RUN npm ci --omit=dev

EXPOSE 3000
USER node
CMD ["node", "build/index.js"]