name: Build ESPlant-Pages
on:
  push:
    branches:
      - main
    paths:
      - "ESPlant-Pages/**"
      - ".github/workflows/build.github-pages.workflow.yml"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Install dependencies
        working-directory: ./ESPlant-Pages
        run: npm install
      - name: Build pages
        working-directory: ./ESPlant-Pages
        run: npm run build
      - name: Deploy to GitHub Pages
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "github-pages: [bot] Deploy ESPlant-Pages"
          commit_options: "--no-verify --signoff"
          file_pattern: docs
          branch: gh-pages
          create_branch: true
          push_options: "--force-with-lease"
