name: Build ESPlant Docker image

on:
  push:
    branches:
      - main
    paths:
      - "ESPlant-Server/**"
      - ".github/workflows/build.esplant.workflow.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Download board artifacts
        uses: actions/download-artifact@v3
        with:
          name: ESPlant-Board
          path: ESPlant-Server/dashboard/public
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/Dennis960/esplant
          flavor: |
            latest=true
          tags: |
            type=sha
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      # GitHub Container Registry
      # https://github.com/docker/login-action#github-container-registry
      -
        name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./ESPlant-Server
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
