name: Build Firmware and Upload Artifact

on:
  push:
    branches:
      - main
    paths:
      - "ESPlant-Firmware/**"
      - ".github/workflows/build.firmware.workflow.yml"
  pull_request:
    branches:
      - main
    paths:
      - "ESPlant-Firmware/**"
      - ".github/workflows/build.firmware.workflow.yml"

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci
        working-directory: ESPlant-Firmware/frontend

      - name: Build Frontend
        run: npm run build
        working-directory: ESPlant-Firmware/frontend

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: frontend
          path: ESPlant-Firmware/data

  build-firmware:
    runs-on: ubuntu-latest
    needs: build-frontend

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download Frontend Artifact
        uses: actions/download-artifact@v2
        with:
          name: frontend
          path: ESPlant-Firmware/data

      - name: Build Firmware
        run: |
          docker run --rm -v $PWD:/project -w /project/ESPlant-Firmware -u $UID -e HOME=/tmp espressif/idf idf.py build

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: |
            ESPlant-Firmware/build/ESPlant-Firmware.bin
            ESPlant-Firmware/build/littlefs.bin
