name: Build ESPlant-Server
on:
  push:
    branches:
      - main
    paths:
      - "ESPlant-Server/**"
      - ".github/workflows/build.esplant-server.workflow.yml"
  pull_request:
    branches:
      - main
    paths:
      - "ESPlant-Server/**"

jobs:
  test-playwright:
    uses: ./.github/workflows/test.playwright.esplant-server.workflow.yml

  docker_publish:
    runs-on: "ubuntu-20.04"
    needs: ["test-playwright"]

    steps:
      - name: Extract branch name
        shell: bash
        run: |
          branch_name="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
          branch_name=$(echo "$branch_name" | sed 's/\//_/g')
          echo "branch=${branch_name}" >> $GITHUB_OUTPUT
        id: extract_branch
      - uses: actions/checkout@v4

      # https://github.com/marketplace/actions/push-to-ghcr
      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: Dennis960/push-to-ghcr@master
        with:
          image_tag: ${{ steps.extract_branch.outputs.branch }}.${{ github.run_number }},${{ steps.extract_branch.outputs.branch }}.latest
          image_name: ${{ github.repository }}/server
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: ESPlant-Server/Dockerfile.build
          context: ESPlant-Server
