name: Deploy ESPlant-Server
on:
  push:
    branches:
      - main
    paths:
      - "ESPlant-Server/**"
      - ".github/workflows/deploy.esplant-server.workflow.yml"
  pull_request:
    branches:
      - main
    paths:
      - "ESPlant-Server/**"
jobs:
  build-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Install api dependencies
        working-directory: ./ESPlant-Server/api
        run: npm install
      - name: Build api
        working-directory: ./ESPlant-Server/api
        run: npm run build
      - name: Upload server artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ESPlant-Api
          path: ./ESPlant-Server/api/dist
  build-dashboard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Install dashboard dependencies
        working-directory: ./ESPlant-Server/dashboard
        run: npm install
      - name: Build dashboard
        working-directory: ./ESPlant-Server/dashboard
        run: npm run build
      - name: Upload dashboard artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ESPlant-Dashboard
          path: ./ESPlant-Server/api/dashboard
  deploy:
    runs-on: ubuntu-latest
    needs: ["build-api", "build-dashboard"]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download api artifacts
        uses: actions/download-artifact@v3
        with:
          name: ESPlant-Api
          path: ESPlant-Api
      - name: Download dashboard artifacts
        uses: actions/download-artifact@v3
        with:
          name: ESPlant-Dashboard
          path: ESPlant-Api/dashboard
      - name: Deploy to server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.HOPPING_KEY }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: "ESPlant-Api/"
          REMOTE_HOST: ${{ secrets.HOPPING_HOST }}
          REMOTE_USER: ${{ secrets.HOPPING_USER }}
          TARGET: ${{ secrets.HOPPING_HOST_PATH }}/api
          SCRIPT_BEFORE: |
            echo "Nothing to do before deploy"
          SCRIPT_AFTER: |
            echo "Install dependencies for api"
            cd ${{ secrets.HOPPING_HOST_PATH }}api
            npm install
            echo "Restarting esplant-service"
            sudo systemctl restart esplant.service
            echo "Create data directory if not exists"
            mkdir -p ${{ secrets.HOPPING_HOST_PATH }}data
