name: Deploy ESPlant-Server
on:
  push:
    branches:
      - main
    paths:
      - "ESPlant-Server/**"
      - ".github/workflows/deploy.esplant-server.workflow.yml"
  pull_request:
    branches:
      - main
    paths:
      - "ESPlant-Server/**"
  workflow_dispatch:

jobs:
  test-playwright:
    uses: ./.github/workflows/test.playwright.esplant-server.workflow.yml

  docker_publish:
    runs-on: "ubuntu-20.04"
    needs: ["test-playwright"]

    steps:
      - uses: actions/checkout@v4

      # https://github.com/marketplace/actions/push-to-ghcr
      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: Dennis960/push-to-ghcr@master
        with:
          image_tag: ${{ github.ref_name }}_${{ github.run_number }}
          image_name: ${{ github.repository }}/server
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: ESPlant-Server/Dockerfile.build
          context: ESPlant-Server

  deploy:
    runs-on: ubuntu-latest
    needs: ["docker_publish"]
    # Only deploy on main branch or manual trigger
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.HOPPING_KEY }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: "ESPlant-Server/docker-compose.yml"
          REMOTE_HOST: ${{ secrets.HOPPING_HOST }}
          REMOTE_USER: ${{ secrets.HOPPING_USER }}
          TARGET: ${{ secrets.HOPPING_HOST_PATH }}/
          SCRIPT_BEFORE: |
            echo "Nothing to do before deploy"
          SCRIPT_AFTER: |
            echo "Deploying with Docker Compose"
            cd ${{ secrets.HOPPING_HOST_PATH }}
            echo "setting SERVER_TAG to ${{ github.ref_name }}_${{ github.run_number }}"
            export SERVER_TAG=${{ github.ref_name }}_${{ github.run_number }}
            echo "Running Docker Compose"
            docker compose pull
            docker compose up -d
            echo "Deployment complete"
