name: Deploy ESPlant-Server
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build ESPlant-Server"]
    branches: ["main"]
    types:
      - completed
env:
  # TODO: extract this to github SECRET
  HOST_PATH: /var/www/hoppingadventure/hopping/esplant/api
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: ESPlant-Server
          path: ESPlant-Server
      - name: Deploy to server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.HOPPING_KEY }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: "ESPlant-Server/"
          REMOTE_HOST: "hoppingadventure.com"
          REMOTE_USER: "hopping"
          TARGET: ${{ env.HOST_PATH }}
          SCRIPT_BEFORE: |
            echo "Nothing to do before deploy"
          SCRIPT_AFTER: |
            echo "Install dependencies for api"
            cd ${{ env.HOST_PATH }}/api
            npm install
            echo "Restarting esplant-service"
            sudo systemctl restart esplant.service
            echo "Create data directory if not exists"
            mkdir -p ${{ env.HOST_PATH }}/data

