name: Export Board with KiCad
on:
  push:
    paths:
      - "Board/Board.kicad_sch"
      - "Board/Board.kicad_pcb"
      - .github/workflows/generate.board.workflow.yml
  workflow_dispatch:
jobs:
  export:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Add KiCad PPA and install KiCad
        run: |
          sudo add-apt-repository --yes ppa:kicad/kicad-dev-nightly
          sudo apt update
          sudo apt install --install-recommends kicad-nightly
      - name: Create dist folder
        run: |
          mkdir -p Board/dist
      - name: Export Board
        run: |
          kicad-cli-nightly sch export pdf Board/Board.kicad_sch -o Board/dist/Board-schematic.pdf
          kicad-cli-nightly sch export svg Board/Board.kicad_sch -o Board/dist/Board-schematic.svg
          kicad-cli-nightly pcb export pdf Board/Board.kicad_pcb --layers F.Cu,B.Cu,F.Silkscreen,B.Silkscreen,User.Drawings,User.Comments,Edge.Cuts -o Board/dist/Board-pcb.pdf
          kicad-cli-nightly pcb export vrml Board/Board.kicad_pcb -o Board/dist/Board.wrl
          kicad-cli-nightly pcb export step Board/Board.kicad_pcb --drill-origin --no-dnp --subst-models -o Board/dist/Board.step
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Board
          path: Board/dist
  upload:
    runs-on: ubuntu-latest
    needs: export
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: Board
          path: Board
      - name: Upload to server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.BLUMY_KEY }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: "Board/"
          REMOTE_HOST: ${{ secrets.BLUMY_HOST }}
          REMOTE_USER: ${{ secrets.BLUMY_USER }}
          # For now, the target is the same as the firmware path
          TARGET: ${{ secrets.BLUMY_FIRMWARE_PATH }}/
        