name: Playwright Tests
on:
  push:
  pull_request:
    branches: [main]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_USER: esplant
          POSTGRES_PASSWORD: esplant
          POSTGRES_DB: esplant_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U esplant"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Set working directory
        run: cd ESPlant-Server
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -U esplant; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done
      - name: Run Playwright tests
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_USER: esplant
          POSTGRES_PASSWORD: esplant
          POSTGRES_DB: esplant_test
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: test-results
          retention-days: 30
